services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "5000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yadn
      MYSQL_USER: admin_username
      MYSQL_PASSWORD: root
    networks:
      - internal
    volumes:
      - mysql_data:/var/lib/mysql

  patient-micro1:
    build:
      context: .
      dockerfile: patient-micro1/Dockerfile

    container_name: patient-micro1
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/yadn
      SPRING_DATASOURCE_USERNAME: admin_username
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
    depends_on:
      - mysql
    networks:
      - internal

  billing_services_1:
    build:
      context: ./billing_services_1
      dockerfile: Dockerfile
    container_name: billing_services_1
    ports:
      - "4001:4001"
      - "9001:9001"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/yadn
      SPRING_DATASOURCE_USERNAME: admin_username
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql
networks:
  internal:

volumes:
  mysql_data:
